/**
 * @file
 * @copyright This code is licensed under the 3-clause BSD license.\n
 *            Copyright ETH Zurich, Laboratory for Physical Chemistry, Reiher Group.\n
 *            See LICENSE.txt for details.
 */
#include <Utils/Geometry/ElementInfo.h>
#include <Utils/Geometry/ElementTypes.h>
#include <pybind11/pybind11.h>

using namespace Scine::Utils;

void init_element_type(pybind11::module& m) {
  pybind11::enum_<ElementType> element_type(m, "ElementType", pybind11::arithmetic(), "Element type enum");

  element_type.value("none", ElementType::none)
      .value("H", ElementType::H)
      .value("He", ElementType::He)
      .value("Li", ElementType::Li)
      .value("Be", ElementType::Be)
      .value("B", ElementType::B)
      .value("C", ElementType::C)
      .value("N", ElementType::N)
      .value("O", ElementType::O)
      .value("F", ElementType::F)
      .value("Ne", ElementType::Ne)
      .value("Na", ElementType::Na)
      .value("Mg", ElementType::Mg)
      .value("Al", ElementType::Al)
      .value("Si", ElementType::Si)
      .value("P", ElementType::P)
      .value("S", ElementType::S)
      .value("Cl", ElementType::Cl)
      .value("Ar", ElementType::Ar)
      .value("K", ElementType::K)
      .value("Ca", ElementType::Ca)
      .value("Sc", ElementType::Sc)
      .value("Ti", ElementType::Ti)
      .value("V", ElementType::V)
      .value("Cr", ElementType::Cr)
      .value("Mn", ElementType::Mn)
      .value("Fe", ElementType::Fe)
      .value("Co", ElementType::Co)
      .value("Ni", ElementType::Ni)
      .value("Cu", ElementType::Cu)
      .value("Zn", ElementType::Zn)
      .value("Ga", ElementType::Ga)
      .value("Ge", ElementType::Ge)
      .value("As", ElementType::As)
      .value("Se", ElementType::Se)
      .value("Br", ElementType::Br)
      .value("Kr", ElementType::Kr)
      .value("Rb", ElementType::Rb)
      .value("Sr", ElementType::Sr)
      .value("Y", ElementType::Y)
      .value("Zr", ElementType::Zr)
      .value("Nb", ElementType::Nb)
      .value("Mo", ElementType::Mo)
      .value("Tc", ElementType::Tc)
      .value("Ru", ElementType::Ru)
      .value("Rh", ElementType::Rh)
      .value("Pd", ElementType::Pd)
      .value("Ag", ElementType::Ag)
      .value("Cd", ElementType::Cd)
      .value("In", ElementType::In)
      .value("Sn", ElementType::Sn)
      .value("Sb", ElementType::Sb)
      .value("Te", ElementType::Te)
      .value("I", ElementType::I)
      .value("Xe", ElementType::Xe)
      .value("Cs", ElementType::Cs)
      .value("Ba", ElementType::Ba)
      .value("La", ElementType::La)
      .value("Ce", ElementType::Ce)
      .value("Pr", ElementType::Pr)
      .value("Nd", ElementType::Nd)
      .value("Pm", ElementType::Pm)
      .value("Sm", ElementType::Sm)
      .value("Eu", ElementType::Eu)
      .value("Gd", ElementType::Gd)
      .value("Tb", ElementType::Tb)
      .value("Dy", ElementType::Dy)
      .value("Ho", ElementType::Ho)
      .value("Er", ElementType::Er)
      .value("Tm", ElementType::Tm)
      .value("Yb", ElementType::Yb)
      .value("Lu", ElementType::Lu)
      .value("Hf", ElementType::Hf)
      .value("Ta", ElementType::Ta)
      .value("W", ElementType::W)
      .value("Re", ElementType::Re)
      .value("Os", ElementType::Os)
      .value("Ir", ElementType::Ir)
      .value("Pt", ElementType::Pt)
      .value("Au", ElementType::Au)
      .value("Hg", ElementType::Hg)
      .value("Tl", ElementType::Tl)
      .value("Pb", ElementType::Pb)
      .value("Bi", ElementType::Bi)
      .value("Po", ElementType::Po)
      .value("At", ElementType::At)
      .value("Rn", ElementType::Rn)
      .value("Fr", ElementType::Fr)
      .value("Ra", ElementType::Ra)
      .value("Ac", ElementType::Ac)
      .value("Th", ElementType::Th)
      .value("Pa", ElementType::Pa)
      .value("U", ElementType::U)
      .value("Np", ElementType::Np)
      .value("Pu", ElementType::Pu)
      .value("Am", ElementType::Am)
      .value("Cm", ElementType::Cm)
      .value("Bk", ElementType::Bk)
      .value("Cf", ElementType::Cf)
      .value("Es", ElementType::Es)
      .value("Fm", ElementType::Fm)
      .value("Md", ElementType::Md)
      .value("No", ElementType::No)
      .value("Lr", ElementType::Lr)
      .value("Rf", ElementType::Rf)
      .value("Db", ElementType::Db)
      .value("Sg", ElementType::Sg)
      .value("Bh", ElementType::Bh)
      .value("Hs", ElementType::Hs)
      .value("Mt", ElementType::Mt)
      .value("Ds", ElementType::Ds)
      .value("Rg", ElementType::Rg)
      .value("Cn", ElementType::Cn);

  element_type.def("__str__", &ElementInfo::symbol);
}
